apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 0.2.3
    chart: sonarqube
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: testing2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
